### *!
#\authors     Дарья Лебедева <daryadosya@yandex.ru>
#\version     0.0.1a
#\date        03.10.2022
#\coopyright  MIT
###

default: clear 005
	   gcc -o 005.exe ./main.c ./005.o

005:
	gcc -c ./005.c

clear:
	   rm -rf ./*.exe ./*.o

doc:
	doxygen ./Doxyfile
