### *!
#\authors     Дарья Лебедева <daryadosya@yandex.ru>
#\version     0.0.1a
#\date        03.10.2022
#\coopyright  MIT
###

default: clear 003
	   gcc -o 003.exe ./main.c ./003.o

003:
	gcc -c ./003.c

clear:
	   rm -rf ./*.exe ./*.o

doc:
	doxygen ./Doxyfile
