### *!
#\authors     Дарья Лебедева <daryadosya@yandex.ru>
#\version     0.0.1a
#\date        03.10.2022
#\coopyright  MIT
###

default: clear 006
	   gcc -o 006.exe ./main.c ./006.o

006:
	gcc -c ./006.c

clear:
	   rm -rf ./*.exe ./*.o

doc:
	doxygen ./Doxyfile
