### *!
#\authors     Дарья Лебедева <daryadosya@yandex.ru>
#\version     0.0.1a
#\date        03.10.2022
#\coopyright  MIT
###

default: clear 008
	   gcc -o 008.exe ./main.c ./008.o

008:
	gcc -c ./008.c

clear:
	   rm -rf ./*.exe ./*.o

doc:
	doxygen ./Doxyfile
