### *!
#\authors     Дарья Лебедева <daryadosya@yandex.ru>
#\version     0.0.1a
#\date        03.10.2022
#\coopyright  MIT
###

default: clear 010
	   gcc -o 010.exe ./main.c ./010.o

010:
	gcc -c ./010.c

clear:
	   rm -rf ./*.exe ./*.o

doc:
	doxygen ./Doxyfile
