### *!
#\authors     Дарья Лебедева <daryadosya@yandex.ru>
#\version     0.0.1a
#\date        03.10.2022
#\coopyright  MIT
###

default: clear 007
	   gcc -o 007.exe ./main.c ./007.o

007:
	gcc -c ./007.c

clear:
	   rm -rf ./*.exe ./*.o

doc:
	doxygen ./Doxyfile
